### ISSUE TITLE
run github actions

### ISSUE THREAD

**Issue by guerlielton-campos** [qoomon/aws-ssm-ec2-proxy-command#13]
Hi, I first congrats a good job 

I have a question it's possible run in github action ? I trying but received errors  

cat: /home/runner/.ssh/id_rsa.pub: No such file or directory
kex_exchange_identification: Connection closed by remote host
Error: Process completed with exit code 255.

I need generate id_rsa.pub into the my actions ? 

I exported id_rsa with 

mkdir -p $HOME/.ssh \
&& echo ***
> $HOME/.ssh/id_rsa \
&& sed -i -e "s#\\\\n#\n#g" $HOME/.ssh/id_rsa \
&& chmod 600 $HOME/.ssh/id_rsa

**Comment by qoomon** [comment]
yes you need to create an ssh key within your github actions first. execute following command to generate a default ssh key
`ssh-keygen -t rsa -b 4096 -N '' -f "$HOME/.ssh/id_rsa"`

**Comment by guerlielton-campos** [comment]
Thank you @qoomon
