### ISSUE TITLE
ec2-instance-connect does not support  ed25519

### ISSUE THREAD

**Issue by DocLM** [qoomon/aws-ssm-ec2-proxy-command#15]
Recent changes suggest to create a ed25519 key. This type of key is not actually supported by ec2-instance-connect and make the script to fail with the following error:

Parameter validation failed:
Invalid length for parameter SSHPublicKey, value: 81, valid min length: 256
kex_exchange_identification: Connection closed by remote host

References from AWS docs and GitHub issues:
- https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-connect-methods.html#ec2-instance-connect-connecting-aws-cli
- https://github.com/aws/aws-sdk/issues/37

**Comment by qoomon** [comment]
oh my bad. I'll fix it

**Comment by qoomon** [comment]
I've reverted the ed25519 changes. thanks for reporting
