### ISSUE TITLE
Powershell script does not work

### ISSUE THREAD

**Issue by asaf050** [qoomon/aws-ssm-ec2-proxy-command#17]
When trying to ssh using the ps1 script, I received an error:
```
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help

Unknown options: -p, &&, cd, ~ubuntu/.ssh, ||, exit, 1
```
![image](https://user-images.githubusercontent.com/7129342/155895545-936ea976-edc8-4f90-bf1f-7fa0a05693c4.png)

And this is the error message from AWS run command:
```
sleep: invalid time interval ‘\r’

Try 'sleep --help' for more information.

mv: cannot stat '.authorized_keys': No such file or directory

failed to run commands: exit status 1
```
SSH config:

```
Host i-* mi-*
  IdentityFile ~/.ssh/id_rsa
  ProxyCommand powershell.exe ~/.ssh/aws-ssm-ec2-proxy-command.ps1 %h %r %p ~/.ssh/id_rsa.pub
  StrictHostKeyChecking no
```

**Comment by qoomon** [comment]
Hi, thanks for reporting. I"m not a PowerShell user, I got this code by a PR. However I'll try to solve it.

**Comment by qoomon** [comment]
It seams like you private key id_rsa has an invalid format

**Comment by qoomon** [comment]
I did some minor changes on the script, feel free to try it once again.
