### ISSUE TITLE
ProxyCommand doesn't work without prior direct log in via (aws ssm start-session --target i-instance)

### ISSUE THREAD

**Issue by jhirn** [qoomon/aws-ssm-ec2-proxy-command#20]
Hello. 

First I'd like to say thanks for this script it has helped me. Second, I'm aware I may actually be facing some configuration issues on my instance here, but wanted to ask the question in case you can shed light on something. 

I wrote a script to generate the `.ssh/config` using our server names for easier location of the box. This is for easier tab-completion when figuring out which box you want to log in to. The entries look like this: 

```
Host core-api-demo-application-server2
  ProxyCommand bash -c "/Users/jhirn/src/tflow/core_api/bin/aws/ssh_via_ssm.sh i-0..... %r %p ~/.ssh/id_rsa.pub"
  StrictHostKeyChecking no
  IdentityFile ~/.ssh/id_rsa
  User jhirn # or ssm-user, see below
```

I've added User so I log in as myself and this works just fine. However, we have some users that are not preconfigured on the machines and still need SSH, so I've switched this from `jhirn` to `ssm-user` which is the base account used when doing `aws ssm start-session`. Logging in as `jhirn` works, but only if I've previous logged into the machine directly with `aws ssm start-session --target XXX)` at least once. When I do this, I'm logged in as `ssm-user`. If I log into the machine as myself prior do doing so, I actually get `No passwd entry for user 'ssm-user'` if I try to `sudo su - ssm-user`.  That kind of makes sense for why it's not working, but I'm just curious why  `AWS-StartSSHSession` via command line logs in the `ssm-user` just fine, but not via `ProxyCommand` without a prior login. Also curious if there's a way to make the AWS-RunSHellScript script create the user when copying the key so the ProxyCommand script will just work. I could just create the `ssm-user` but want to make sure it's done in the same way `aws ssm start-session` would do it. 

Happy to provide more details such as `ssh -v output`. I have a hunch the `AWS-RunShellScript` to copy the key may be failing, or that it could be enhanced to add the `ssm-user` if they don't already exist, but a bit stumped atm. 

Thanks!

**Comment by jhirn** [comment]
After some digging this came up https://github.com/aws/amazon-ssm-agent/issues/342. It's quite the chicken/egg however as I can't do `AWS-StartSSHSession` without the key being there via in ProxyCommand. It doesn't appear `AWS-RunShellScript` is failing but it's possible that it is. In the least I know it's not creating the `ssm-user` propoerly for `start-session` to succeed on a first run via ProxyCommand .

**Comment by qoomon** [comment]
@jhirn have you tried https://github.com/qoomon/aws-ssm-ec2-proxy-command/blob/master/ec2-instance-connect/aws-ssm-ec2-proxy-command.sh ?

**Comment by qoomon** [comment]
btw I think the default user is `ec2-user`

**Comment by qoomon** [comment]
do you really want to create an individual user account on the machine for every user connecting?

**Comment by jhirn** [comment]
Wow thanks for the responses. Really apreciate the fact you've replied multiple times =). 

Let me try the `ec2-instance-connect send-ssh-public-key` flavor of the script. I'm assuming that it would need `ssm-user` to exist but I'm totally stumped at this point. 

I had the though of trying to create the user manually via `useradd`.  I know the agent also adds that user to sudoers and unsure what else it might need for it to actually be a "true" `ssm-user`. There doesn't seem to be a way to invoke the agent and simulate a first `start-session` other than doing `aws start-session`. Kind of a bummer. 

Definitely do not want to need to have an individual user account on each machine, but I already have one for most and we are in the process of completely redoing out infrastructure so this was just supposed to be a stop gap and it's driving me bananas.

**Comment by jhirn** [comment]
So I added the following and it works as expected so far. Hopefully there's not any extra wiring up of the user that I'm leaving out but does what I need in the interim. 

```bash
useradd -m ${ssh_user}
echo \\\"#User rules for ssm-user\\\" > /etc/sudoers.d/ssm-agent-users
echo \\\"ssm-user ALL=(ALL) NOPASSWD:ALL\\\" >> /etc/sudoers.d/ssm-agent-users
```

**Comment by jhirn** [comment]
Going to close this. It may help some to find in the issues but I'm not sure it's something you'd want to add to the script. Perhaps a Readme entry wouldn't hurt?
