### ISSUE TITLE
ssh handshake expose on mac

### ISSUE THREAD

**Issue by lisbethw1130** [qoomon/aws-ssm-ec2-proxy-command#5]
Not really sure whether the words are correct.
But I found that if there's no `sh -c` wrap the session create command, it will expose the handshake process and cause error like: protocol mismatch

I have to use
```
sh -c "aws ssm start-session \
  --target "${ec2_instance_id}" \
  --document-name 'AWS-StartSSHSession' \
  --parameters "portNumber=${ssh_port}""
```
instead of
```
aws ssm start-session \
  --target "${ec2_instance_id}" \
  --document-name 'AWS-StartSSHSession' \
  --parameters "portNumber=${ssh_port}"
```

**Comment by qoomon** [comment]
me and my colleagues are using a mac as well we are not facing this problem.
may you gan give some more details to reproduce this behaviour?

**Comment by qoomon** [comment]
@lisbethw1130 may you can provide some error logs?

**Comment by qoomon** [comment]
@lisbethw1130 wich os and wich shell do you use

**Comment by lisbethw1130** [comment]
hmm, I can't reproduce the situation now, seems that it's not the problem, I will to close this issue
thanks for helping from @qoomon
