### ISSUE TITLE
Consider applying a license

### ISSUE THREAD

**Issue by kastork** [qoomon/aws-ssm-ec2-proxy-command#6]
Hello, and thanks for this.
Would you consider applying a license or a public domain dedication to this repository?

I ask because, as a user in an academic environment, my projects come (as a matter of routine) under scrutiny for copyright compliance and plagiarism.  Having a license or dedication is very useful when this happens.

**Comment by qoomon** [comment]
Sure see https://github.com/qoomon/aws-ssm-ec2-proxy-command/blob/master/LICENSE

**Comment by kastork** [comment]
Thanks!
